#!/usr/bin/env bash
ZABBIX_USER="SuperUserDo" #change
ZABBIX_PASS="ls32bits"  #change
ZABBIX_API="http://192.168.1.103/zabbix/api_jsonrpc.php"
#HOST_ZABBIX=$1
LISTA_TXT=$1
ZABBIX_AUTH_TOKEN=$(curl -s -H  'Content-Type: application/json-rpc' -d "{\"jsonrpc\": \"2.0\",\"method\":\"user.login\",\"params\":{\"user\":\""${ZABBIX_USER}"\",\"password\":\""${ZABBIX_PASS}"\"},\"auth\": null,\"id\":0}" $ZABBIX_API |  jq -r .result)

old_IFS=$IFS
        IFS=$'\n'

for k in $(awk '{print $2}' ${LISTA_TXT})

  do

GET_HOST_ID=$(curl -s -H  'Content-Type: application/json-rpc' -d "
{
    \"jsonrpc\": \"2.0\",
    \"method\": \"host.get\",
    \"params\": {
        \"filter\": {
            \"host\": [
                \"${k}\"
            ]
        }
    },
    \"auth\": \"${ZABBIX_AUTH_TOKEN}\",
    \"id\": 1
}" ${ZABBIX_API} | jq .result[].hostid | sed 's/\"//g' ) ;


        for i in $(cat ${LISTA_TXT} | sort  | uniq | grep $k | sort -rn | awk 'NR==1{print $0}')

                do

HOST_LISTA=$(echo $i | awk '{print $2}')
COR_TEMPLATE=$(echo $i | awk '{print $1}')
ID_TEMPLATE=$(echo $i | awk '{print $3}')

  if [ $COR_TEMPLATE -eq 1 ]

        then exit 1

                else

GERA_LOG_LINKA_TEMPLATE=$(curl -s -H 'Content-Type: application/json-rpc' -d "

{
    \"jsonrpc\": \"2.0\",
    \"method\": \"host.massadd\",
    \"params\": {
        \"hosts\": [
            {
                \"hostid\": \"${GET_HOST_ID}\"
            }
        ],
        \"templates\": [
            {
                \"templateid\": \"${ID_TEMPLATE}\"
            }
        ]
    },
    \"auth\": \"${ZABBIX_AUTH_TOKEN}\",
    \"id\": 1
}" ${ZABBIX_API} | jq )

                if grep -i "error" <<< $(echo -e ${GERA_LOG_LINKA_TEMPLATE} )

        then echo -e "\"Host:\t${HOST_LISTA}:\tnao encontrado\"" | tee -a logs.jayquill

                else

echo -e ${GERA_LOG_LINKA_TEMPLATE} | jq .result[][] | sed "s/^\"/\"Host:\t${HOST_LISTA}:\t/g" | egrep -vi "error.*"| tee -a logs.jayquill

fi
  fi

        done

done
IFS=${old_IFS}
