#!/usr/bin/env bash
ZABBIX_USER="Admin" #change
ZABBIX_PASS="zabbix"  #change
ZABBIX_API="http://#######IP########/api_jsonrpc.php"
#HOST_ZABBIX=$1
#MACRO_NAME=$2
#MACRO_VALUE=$3

ZABBIX_AUTH_TOKEN=$(curl -s -H  'Content-Type: application/json-rpc' -d "{\"jsonrpc\": \"2.0\",\"method\":\"user.login\",\"params\":{\"user\":\""${ZABBIX_USER}"\",\"password\":\""${ZABBIX_PASS}"\"},\"auth\": null,\"id\":0}" $ZABBIX_API |  jq -r .result)

old_IFS=$IFS
        IFS=$'\n'

for l in $(awk -F";" '{print $1}' itens  | sort -u | uniq )
do

HOST_ZABBIX=${l}

GET_HOST_ID=$(curl -s -H  'Content-Type: application/json-rpc' -d "
{
    \"jsonrpc\": \"2.0\",
    \"method\": \"host.get\",
    \"params\": {
        \"filter\": {
            \"host\": [
                \"${HOST_ZABBIX}\"
            ]
        }
    },
    \"auth\": \"${ZABBIX_AUTH_TOKEN}\",
    \"id\": 1

}" ${ZABBIX_API}| jq | grep -E "\"hostid.:" | awk -F"\"" '{print $4}')

for i in $(awk -F";" '$1 == "'${l}'" {print $0}' itens)
	do
	MACRO_NAME=$(echo ${i} |awk -F";" '{print $2}' )
	MACRO_VALUE=$(echo ${i} |awk -F";" '{print $3}' )


curl -s -H  'Content-Type: application/json-rpc' -d "
{
    \"jsonrpc\": \"2.0\",
    \"method\": \"usermacro.create\",
    \"params\": {
        \"hostid\": \"${GET_HOST_ID}\",
        \"macro\": \"{\$${MACRO_NAME}}\",
        \"value\": \"${MACRO_VALUE}\"
    },
    \"auth\": \"${ZABBIX_AUTH_TOKEN}\",
    \"id\": 1
}" ${ZABBIX_API}

done

	done
IFS=${old_IFS}
