#!/usr/bin/env bash
ZABBIX_USER="Admin"
ZABBIX_PASS="zabbix"
ZABBIX_API="http://#########IP###########/api_jsonrpc.php"
ZABBIX_HOST=$1
NAME_TAG=$2
VALUE_TAG=$3
VALUE_TRIGGER_NAME=$4
ZABBIX_AUTH_TOKEN=$(curl -s -H  'Content-Type: application/json-rpc' -d "{\"jsonrpc\": \"2.0\",\"method\":\"user.login\",\"params\":{\"user\":\""${ZABBIX_USER}"\",\"password\":\""${ZABBIX_PASS}"\"},\"auth\": null,\"id\":0}" $ZABBIX_API |  jq -r .result)
VALUE_TRIGGER=$(echo $VALUE_TRIGGER_NAME | grep -i "enabled" &> /dev/null && echo 0 || echo 1)

VALUE_TRIGGER_TEST=$(echo $VALUE_TRIGGER_NAME | grep -iE "(Enabled|Disabled)" &> /dev/null ; echo $? )

    if [ $VALUE_TRIGGER_TEST -ne 0 ]
    	then
    echo "Terceiro parametro Enabled/Disabled!"
    exit 1
    	else

    GET_HOST_ID=$(curl -s -H  'Content-Type: application/json-rpc' -d "

    {
    \"jsonrpc\": \"2.0\",
       \"method\": \"host.get\",
        \"params\": {
         \"output\" : [\"hostid\"],
            \"filter\": {
              \"host\": [
             \"${ZABBIX_HOST}\"
        ]
        }
        },
        \"auth\": \"${ZABBIX_AUTH_TOKEN}\",
        \"id\": 1
    }" ${ZABBIX_API} | jq .result[].hostid
    )
    ####

    if [ -z $GET_HOST_ID  ]

    	then
    echo "Host $ZABBIX_HOST nao existe!!!"

    exit 1

    	else

    ###
    GET_TRIGGER_ID=$(
    curl -s -H  'Content-Type: application/json-rpc' -d "

    {
        \"jsonrpc\": \"2.0\",
        \"method\": \"trigger.get\",
        \"params\": {
               \"output\":[
                 \"triggerid\"
            ],
              \"selectTags\": \"extend\",
    	   \"tags\" : [{\"tag\": \"${NAME_TAG}\", \"value\": \"${VALUE_TAG}\", \"operator\": 1}],
    	   \"hostids\": [
               	${GET_HOST_ID}
        ]
        },
        \"auth\": \"${ZABBIX_AUTH_TOKEN}\",
        \"id\": 1

    }" ${ZABBIX_API} | jq .result[].triggerid 
    )

    if [ $(echo ${GET_TRIGGER_ID} | wc -c) -le 1 ]

            then
    echo "Host $ZABBIX_HOST existe, nao ha triggers para a tag ${NAME_TAG} valor  ${VALUE_TAG}!!!"

    exit 1

            else



    for j in ${GET_TRIGGER_ID[@]}

    	do

    echo -n "${VALUE_TRIGGER_NAME} : TriggerID :"

    curl -s -H  'Content-Type: application/json-rpc' -d "

    {
        \"jsonrpc\": \"2.0\",
        \"method\": \"trigger.update\",
        \"params\": {
         \"triggerid\": ${j},
            \"status\": ${VALUE_TRIGGER}
        },
        \"auth\": \"${ZABBIX_AUTH_TOKEN}\",
        \"id\": 1
    }" ${ZABBIX_API} | jq .result.triggerids[] 

    done

    fi

    fi

    fi
